### PR TITLE
Feature/bookmark endpoints tests

### PR DESCRIPTION
**Pull request by dominthebox**
## Description

I discovered it can be quite tricky to mock the the req.body received from Okta to successfully pass the authRequired middleware in order to test the bookmark router endpoints successfully. So in this PR I commented out my bookmarks endpoint tests and left comments on where it stands and potentially how to move forward for whoever works on this test suite next. 

Many thanks to @christina-yun @paulstgermain @ryan-hamblin for assisting in the troubleshooting of this issue. 

[Loom video PR walkthrough](https://www.loom.com/share/a807230c615a48ec9ab448414c239650)

Fixes # (issue)
attempts to flesh out bookmarks endpoints tests

## Type of change
adds comments to where the testing suite is left off

- [x] New feature (non-breaking change which (does not yet) adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by jinjahninjah — APPROVED** [review]
Nice tests! Looks great!

**Review by jMisch44 — APPROVED** [review]
Looks good.

**Review by Grantzho — COMMENTED** [review]
Great work. Nice comments

**Review by christina-yun — APPROVED** [review]
This looks great so that other people can pick it up. Thanks for putting in the article we referenced

**Pull request merged**
