### PR TITLE
Feature/new profile tests

### PR DESCRIPTION
**Pull request by christina-yun**
## Description
Finished testing files for both the endpoints and the model to ensure that if any changes are made to models or routes, that maintenance will be easy.

This PR integrates the following:
- Fixed the testing environment in knex config file as the directories kept trying to migrate and seed from folder that the repo was placed in
- Adding unit tests for profiles to test the shape of data and monitor it if it changes
- Added delete unit tests for profile router

Fixes # (issue)
- knex testing environment has been changed so that integration tests will work
- cleans up some of the models and migrations that aren't needed

https://www.loom.com/share/e1fe264e71a5471aa6d85a41fa027797
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by Klove-A** [comment]
Is this pull request ready for review? It says it's a draft I'm not sure what that means.

**Comment by christina-yun** [comment]
Have to re-record my Loom -- my original PR video had no sound

**Review by dominthebox — APPROVED** [review]
Excellent work @christina-yun, great job identifying the pathing issue in the Knex file in the configurations folder. The code is well written and DRY, it accurately tests the shape of profiles data when testing the profiles models as well tests the proper responses when calling the profiles routers.

**Review by MMostella — APPROVED** [review]
Rock on Christina! Everything looks great!

**Review by jMisch44 — APPROVED** [review]
Looks good. Nice job with writing all these tests!

**Pull request merged**
