### PR TITLE
Bug/no file table for seed

### PR DESCRIPTION
**Pull request by christina-yun**
## Description
After figuring out that seeds wouldn't run, looked into it and saw that the problem was that there was no "files" table for "files" seed file. After consulting previous BE eng on this project, it was confirmed that is a planning artifact that got moved to the DS API.

As a result, we are deleting the seed file and the proceeding seed file was renamed accordingly.

Edit: Adding Loom video walkthrough of the pull request 
https://www.loom.com/share/62fcca0664f0420c8b2c72b184f30bc7

Fixes # (issue)
npm run seed would not seed but npm migrate and rollback worked fine

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by stu-wd** [comment]
Great catch @christina-yun @dominthebox

**Review by MMostella — APPROVED** [review]
Such a good catch from simply code reviewing!

**Review by steinmikey — APPROVED** [review]
Good catch on the unnecessary seed file! The commit message might be better if it's shorter i.e. 'removes unneeded seed file'

**Review by paulstgermain — CHANGES_REQUESTED** [review]
I can't technically review/approve of this PR without a Loom recording walking through the changes here! Please upload such a video walkthrough as soon as you can! 😄

**Comment by christina-yun** [comment]
@paulstgermain I've added the Loom video of myself walking through the changes and the conversations leading up to the changes. I believe this is ready to merge!

**Review by paulstgermain — APPROVED** [review]

**Pull request merged**
