### PR TITLE
Feature/admins server tests

### PR DESCRIPTION
**Pull request by christina-yun**
## Description
Created admin server tests that test the admin router endpoints
https://www.loom.com/share/4711efec25ff4a64ac352aa15a27a698

Fixes # (issue)
- The lack of testing across all the router functions

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Klove-A — APPROVED** [review]
Great job! Code looks clean and consistent, I love the detailed video. I appreciate that you included numerous detailed comments, but it might've been nice to see a commit for each time you finish a test.

**Review by jMisch44 — APPROVED** [review]
Looks good! Nice job with the video, very descriptive while walking us through your changes and the reasons for them.

**Review by steinmikey — APPROVED** [review]
I like the improved naming in the model/router files, and your video was a very helpful walk through of the tests you wrote. Awesome job!

**Comment by stu-wd** [comment]
I really appreciate the fact that you went back and changed the model functions to start with a verb and avoided the redundancy/weird sound of `Admin.adminById` or what have you, Overall, this is pretty awesome work. It shows understanding that you made sure to check the response. I really appreciate how thorough the video is, too.

**Review by dominthebox — APPROVED** [review]
Ahh so much closer to 100% coverage! haha Great work and as always excellent video walking us through your process for creating and writing new tests @christina-yun

**Pull request merged**
